// app/layout.js у ЧИСТОМУ проекті railway-test (максимально спрощена версія)

// import { GeistSans } from 'geist/font/sans'; // ВИДАЛЯЄМО або КОМЕНТУЄМО
// import { GeistMono } from 'geist/font/mono'; // ВИДАЛЯЄМО або КОМЕНТУЄМО
import "./globals.css"; // Залишаємо, якщо globals.css у чистому проекті стандартний і порожній або майже порожній

// export const metadata = { // Можна залишити, це не має викликати проблем
// title: "Create Next App",
// description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Прибираємо класи шрифтів з body для цього тесту */}
      <body>
        {children}
      </body>
    </html>
  );
}